#   -*- mode: org; fill-column: 60 -*-

#+TITLE: FRBR & MARC
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/bmf/bmf-frbr-and-marc.org
:Created:   2017-11-15T14:33@Prek Leap (11.642600N-104.919210W)
:ID:        be4151b5-6cba-4cbb-898b-170c585f292e
:VER:       564003247.278974270
:GEO:       48P-491193-1287029-15
:BXID:      proj:UCW4-2406
:Class:     deploy
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction



#+begin_quote
Cataloging records come in three types: 1) Bibliographic records,
which contain information describing a book, serial, sound recording,
videorecording, etc.; 2) Authority records, which contain standardized
forms for names, titles, and subjects that are used on bibliographic
records and provide cross references in catalogs; 3) Holdings records,
which contain information about whether an institution holds or can
provide access to bibliographic items, in both physical and electronic
forms, which parts of a bibliographic item it holds, and where to find
them.

-- [[https://www.loc.gov/marc/umh/UMHpt1-6.html][Understanding MARC Holdings Records]] | LOC
#+end_quote

 - [[https://www.loc.gov/marc/umh/UMHpt1-6.html][Understanding MARC Holdings Records]] | LOC
 - [[https://www.loc.gov/marc/umb/][Understanding MARC Bibliographic]] | LOC
 - [[https://www.loc.gov/marc/uma/][Understanding MARC Authority]] | LOC

#+begin_src bibtex
@article{coyle:2004future,
  title={Future considerations: the functional library systems record},
  author={Coyle, Karen},
  journal={Library hi tech},
  volume={22},
  number={2},
  pages={166--174},
  year={2004},
  publisher={Emerald Group Publishing Limited}
}
#+end_src


* The Art of Reading Bibliographies

After reading Eco's book /How to Write a Thesis/ it began to dawn on
me that bibliographies are far more than lists of books consulted or
read.  They are a subtle means of gauging the validity of a work and
the biases at play that determine what was put in and what was left
out.  If you created a graph database of surrounding keyword text
where something was cited, and then do the same for all works on the
same topic, you would get a very interesting understanding how a
subject is understood over time.

* Cascade

FRBR metadata should cascade so that information is inherieted from
the hierarchical record above it and that information can be
superceded by different information which is then inherited by records
below it.

#+begin_quote
Viewing the FRBR design as object- oriented, however, allows
us to make use of the concept of ``inheritance'' in which
qualities and data elements of higher levels are inherited
by the linked levels below them. In this way, every
expression inherits the elements associated with the work,
and manifestations inherit those of the expression and the
work.

-- Future considerations: the functional library systems
   record | Karen Coyle (2004)
#+end_quote


* MARC Assumptions

The ubiquitious MARC record was built on a number of assumptions of
how we understood the world at the time that it was devised.  Many of
those assumptions we wrong, or a product of it's meliu that does not
reflect the bibliographic information of an item at the time it was
first created or published.  We are no longer restricted to what fits
on a 3X5" index card, or soon, even the time restraints of catalogers.
For new works, cataloging is often done by publishers before something
is published.  The internet also makes it easy for libraries to share
records so if something has been cataloged once the record can be used
by everyone.

* Version Control

Records need to incorporate version control -- so that as records
change over time, previous records are still available for use in
certain contexts.  Version control also makes it easier for changes to
propagate around the world and stay in sync.

* Authority Records

inverting names makes no sense in electronic records, what does make
sense is to break names into parts -- and at least identify the family
or collective name.  The family name is a abberation of the state as a
means of making people as James Scott likes to say /legible/ to the
state so that they can be better controlled.  There are still pockets
in the world where there are no cannonical names for people in day to
day life, and that a name recorded on a state record and used as an id
might be a poor choice for use as a primary identifier.  Names change
over time.  A childhood friend of mine was called "Ricky" until he
entered university and preferred to be called "Richard" thereafter.
My father was known as "Bud" to family friends and colleagues, and
"Uncle Buddy" to my nieces and nephews, though his baptismal name and
state name was "George".  I am called by the first half of my middle
name "Brad" though my state name is "James Bradford".  Authority
Records need to become more flexible with names.  There is no way of
knowing how names will change over the next five hundred years, so it
is important we find a better way of dealing with them today and
recognize that a name is a label that may or may not change over time.

* Subject Records

Subject records need to change as well -- subject names change in
meaning over time, sometimes dramatically.  So it is important that
any subject heading is tired to a definition and further placed into
the context of where and when it was used that way.  A subject heading
should be capable of have multiple definitions as we do in
dictionaries.

* Place Records
 
Place names in bibliographic records need to change so that it points
to lat lon coordinates on a planet, and then link to the place name
that that location used at the time of publication.

Over time this will change as well -- in this way, the place of
publication for Bradford's "Of Plymouth Plantation" would be
"Massachusetts Bay Colony" but the place for the "Mayflower Compact"
would be an unnamed location that is called "Plymouth, Massachusetts"
today.

* Document Source and Rendered

Bibliographic records today make no distinction between the
source code that a manifestation is generated from.

Blocks of set type would be considered source, as would
photographic negatives.  But today the source could be in a
variety of markup systems from html, XML, TEI, LaTeX or even
a proprietry format such as MS Word or Adobe's InDesign.

This source code, when available should be linked to the
expression, because it is used to generate the
manifestation.

But in another way, the source file is also an item, that
points to something that you can download a copy of.

The best way to deal with this is to create a new record
time that is a type of item record for src files which are
linked to expressions and not manifestations.

Wikipedia points links to images, not to the image, but to
the record that describes the image.

* Record Structure Notes

/works/ are mutually exclusive and are not bound to a physical object

 - an introduction is a separate work from the main body of text
   it introduces.
 - decorative illustrations are a separate work from the work
   they illustrate
 - critical notes, comentary etc are a separate works.


/expressions/ can be made up of one or more works

minor changes to a work -- that can be summed up in a list of a couple
pages in length should be ignored when determining if something should
be a separate expression or not.  Those differences are important, but
not for cataloging.  They can eventually be incorporated as diffs from
the reference text.  This will eventually be automated and will make
life for scholars far easier and identify how errors and corrections
propagate through editions over time.


/manifetations/ are specific editions of an expression

/items/ are specific physical or electronic instances of a manifestation


  - Work 1:  A Christmas Carol
  - Work 2:  Introduction [to A Christmas Carol] Melissa Samson
  - Work 3:  Introduction [to A Christmas Carol] Wingo Lam
  - Work 4:  Illustrations [to A Chrismas Carol] Bai Ling Chan


  - Exp  1:  A Christas Carol
    - primary work      :  Work1
    - supplemental works:  Work2, Work4

  - Man  1:
    - BT Exp 1
    -
