#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Geographic Encoding (BMF Documentation)
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name:      /home/deerpig/proj/chenla/bmf/bmf-geo.org
  :Created:   2017-05-06T18:29@Prek Leap (11.642600N-104.919210W)
  :ID:        2e07d5c2-d057-4a6f-9314-11c18ab2294c
  :VER:       547342248.778280649
  :GEO:       48P-491193-1287029-15
  :BXID:      LXD0-1288
  :TS:        chenla.org/ts/bmf
  :CUSTOM_ID: Geographic_Encoding_(BMF Documentation)
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction



http://www.latlong.net/lat-long-utm.html
https://www.daftlogic.com/sandbox-google-maps-find-altitude.htm


http://www.latlong.net/c/?lat=11.642551&long=104.919203
UTM: 48P 491193.09mE 1287029.38mN 15mE (pnca office)
http://www.latlong.net/c/?lat=11.642788&long=104.918637
UTM: 48P 491131.40mE 1287055.60mN 24mE (4th floor pnca flat)


BMF uses the Universal Transverse Mercanter coordinate system for all
geographic coordinates.

 - [[https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system][Universal Transverse Mercator coordinate system]] | Wikipedia
 - [[https://www.maptools.com/tutorials/utm/quick_guide][A Quick Guide to Using UTM Coordinates]] | Maptools

#+begin_quote
If your using a large scale map, you have UTM coordinates information,
and your peers haven't already made the decision for you, then UTM is
likely to be your best bet.

Some of the advantages of UTM coordinates include...

  - Square grids
  - East-West units of measure are the same as North-South units
  - Decimal based, no fussing with minutes and seconds.
  - Coordinates translate directly to distances on the ground.
  - Coordinate precision is easily understood. No need to wonder what
    distance a tenth of a second of longitude represents.
  - It's easy to abbreviate coordinates when working in a small area.

-- [[https://www.maptools.com/selecting_a_coordinate_system][Selecting a Geographic Coordinate System]] | maptools
#+end_quote



 48P-491193-1287029-15

 zone[-]easting[-]northing[-]elevation


* Elevation

 - [[https://en.wikipedia.org/wiki/Elevation][Elevation]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Geoid][Geoid]]     | Wikipedia
 - [[https://en.wikipedia.org/wiki/International_Terrestrial_Reference_System][International Terrestrial Reference System]] | Wikipedia

Elevations are traditionally given on earth as feet or meters above a
geoid (a geographical reference point) which in earth is usually sea
level.  Height is measurment measured from the ground, such as a
building or person, while altitude is typically used for objects which
are above the ground, but not on it, such as a balloon, airplane or
satellite .

Sea leel will change over time -- we need a means of establishing what
sea level is for a given period of time....

Next -- when you are in a building, you are xx meters above the ground
which is above sea level.

So if you are in a manmade structure we need a different notation

  15+9m would be 15 meters above sea level and 9 meters above ground
  level.

perhaps we add the level number:

  15+9m=4f

Buildings are more about what number floor, rather than how many
meters above ground.  But the height of floors varies considerably.

So what are we trying to do here?  Elevation, height and altitude are
good within each context -- but don't translate very well between each
other.  If BMF is to be a long term and universal system -- we will
need a notation that works across all of these contexts without being
losey -- this isn't a cadastral map...

For earth -- sea level is extremely important information -- so
perhaps we could use a sea level epoch -- the sea level that
corresponds to the time epoch (in our case that is the year 2000).

And after reading up on these things, there is no one size fit all --
we just need to have everything recorded so we know how things are at
a given moment relative to another moment.
