#   -*- mode: org; fill-column: 60 -*-
#+TITLE: 
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/bmf/bmf-header.org
  :Created:   2017-05-07T11:26@Prek Leap (11.642600N-104.919210W)
  :ID:        93092cd2-4efd-4120-bc26-8b095af5d93e
  :VER:       547403241.293958328
  :GEO:       48P-491193-1287029-15
  :BXID:      [[proj:GKX8-2200]]
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

* test
  :PROPERTIES:
  :CUSTOM_ID: _()
  :Created:   2017-05-07T07:01@Prek Leap (11.642600N-104.919210W)
  :ID:        211c3e4a-c31a-41c0-b11f-720f5b74a447
  :STAMP:     547387365.459017524
  :GEO:       48P-491193-1287029-15
  :BXID:      [[proj:MBG1-0425]]
  :END:

  :TREE:
  :UF:  
  :BTI: [[bmf:burr]] [[bmf:work]]
  :BT:
  :NT:  no need for narrower terms -- the db will find those
  :RT:
  :END:


* Attribution Group

| BY  | author/owner |
| BYA | author       |
| BYC | contributor  |
| BYO | owner        |
| BYE | editor       |
| BYT | translator   |


* Language

 - [[https://en.wikipedia.org/wiki/Lists_of_languages][Lists of languages]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Ethnologue][Ethnologue]] | Wikipedia
 - [[https://www.ethnologue.com/][Ethnologue]] | Languages of the World
 - [[http://www-01.sil.org/iso639-3/download.asp][ISO 639-3 Downloads]] | SiL International
 - [[https://en.wikipedia.org/wiki/ISO_639:a][ISO 639:a]]  Wikipedia
 - [[https://en.wikipedia.org/wiki/List_of_ISO_639-5_codes][List of ISO 639-5 codes]] | Wikipedia
 - [[http://glottolog.org/][Glottolog 3.0]]

Language settings are not binary, they should be a list of languages
used in the document, with the primary language being first followed
by other languages used in the Burr.

Usually language settings only determine character sets, fonts and
whih languages that GUI labels, menus, and documentation are written
in.  But I hope that it will become an important part of duck tests,
in determining context, and determine if a fnord is true or not.


| LANG | language |


* Global Group

| BMF       | BMF version      |
| ENCODE    | encoding method  |
| CELESTIAL | Celestial Body   |
| UNIVERSE  | Universe         |
| UNITS     | Measuring System |


I'm really not sure about this.  At the moment everything is unicode
and unicode will be with us for the foreseeable future and is making
heroic efforts to be global and inclusive (even though they won't
include Klingon :)).

But it's also something that we need to make explicit -- even if it's
only set at the top level of each bramble -- though I'm not sure if it
should be indexed -- because it it's set at the top level, then every
burr in the bramble inherits it and you will have a triple for each
and every burr that includes encoding in the dbase.

This becomes a bit of a map-territory thing.  In that if every item in
the db has the same entry, it is basically useless.

So instead we should perhaps use a trick from TEI and create a group
that includes assumptions for all burrs in a bramble and each burr
points to that -- so at least we then only have to do this one time
and that will be that.  But I suppose that eventually we will have
brambles that have other encodings that we can't anticipate and that
they will have to be interoperable with the odd bramble that pops up
from some long forgotten archive that will need to be converted.  And
if that bramble is not complete, it would be better to have this info
included explicitly.  Will this really be /that/ much overhead?
Afterall, there is an encoding line in how many hundreds of billions
of web pages....  Same goes for the BMF version number and a handful
of other things.

But if we do include things like including what star we are on, what
universe etc -- those don't need to be indexed.  So yes, those can go
into a non-indexed set of records that are part of the bramble, but
will not be included in every burr.

We can then add a means for adding and deleting these things from
being indexed -- so we would turn it on for say Cassini or
Pathfinder's brambles, because they are not on earth -- so it becomes
an exception in their case.  Eventually, once we have substantial
numbers of people living throughout the solar systems the celestial
body will be an important item to include in all burrs.  

Same goes for virtual worlds set in alternate universes -- this is
already significant and will become increasingly significant once
emersive VR becomes common place.  That happens in those universes
needs to be internally consistent which is difficult unless you can
change any number of basic assumptions about the world.

* Permissions/Access

| RW  | read/write         |
| RWX | read/write/execute |
| R   | read               |
| W   | write              |
| X   | execute            |

  owner
  group
  other





