#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:  BMF | TOC

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

* Table of Contents
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/bmf/index.org
:Created:   2017-02-06T09:41@Prek Leap (11.642600N-104.919210W)
:ID:        c10d3a29-5475-45c7-a604-707d89f426c5
:VER:       551917936.623012821
:GEO:       48P-491193-1287029-15
:BXID:      proj:DHY4-0486
:Class:     deploy
:Entity:    toc
:Status:    wip 
:Licence:   MIT/CC BY-SA 4.0
:END:


 - [[./bmf-header.org][Header]]
 - [[./bmf-geo.org][Geographic Encoding]]
 - [[./bmf-notes.org][Notes]]
 - [[./bmf-frbr-and-marc.org][FRBR & MARC]]


#+begin_src emacs-lisp

'("ts:subject" "ts:predicate" "ts: object" 
  ((bmf:id     . "uuid" )     ;; uuid+ver (microseconds) 
   (bmf:owner  . "value")     ;; valid identity, label, or url 
   (bmf:group  . "group")     ;; groups who have access
   (bmf:stamp  . "stamp")     ;; time-place stamp
   (bmf:agent  . "agent")     ;; entity that created quad
   (bmf:action . "action")    ;; action used to create quad
   (bmf:src    . "source")    ;; where triple originated
   (bmf:cite   . "citataton") ;; authority src is citing
   (bmf:access . "OOGGWW")    ;; nix style permissions
   (bmf:prob   . "xxx")       ;; probablistic-weight
   (bmf:conf   . "xxx")       ;; confidence-weight
   ))
#+end_src

Weights:

 -  confidence-weight
 -  probablistic-weight 

hunches:

It's worthless for humans to state numerical preferences.
All sorts of cognitive biases kick in.  But it's not bad to
provide a hunch which a baysian algorthm can use as a
starting point to determine certainty and propability.

So we will use very basic words to indicate a hunch that a
statement is true or false, and certainty is low medium or
high.  Some people will want to use more precision but at
the moment I don't see helping much and will likely make
things worse.  After all this is a hunch and hunches are
best guesses.

   true|false  nil|low|medium|high

** inline markup

markup statements within a text.  A statement is any
assertion that something is true or false


[Prai Yut] was born on [20 feb 2044] in [Bangkok-Phuket
Hospital] at 9:22 in the evening.

   So:
        sub:  per:PraiYut_Jaksan 
        pre:  rel:born
        obj:  dt:2044-2-20:21:22
        src:  self

        sub:  per:PraiYut_Jaksan
        pre:  rel:born
        obj:  geo:Bangkok_Phuket_Hospital
        src:  self

Always try to place the markup on the object.

---

What if we put the metadata at the end of the document,
together with the notes and bibliography?  

  - notes       :fn:
  - references  :ref:
  - statements  :stmt:
  - links       :lnk: rich links?

in org we can then do using subheadings with property boxes

When we create 


#+begin_example
**   key                                                              :fnord:
:PROPERTIES:
:ID:    a7ac9a99-8aa4-4eb2-9108-a192b4441400
:sub:   per:PraiYut_Jaksan 
:pred:  rel:born
:obj:   dt:2044-2-20:21:22+7  geo:Bangkok_Phuket_Hospital
:src:   file:projects.org::**heading
:ref:   yut:2044birth-cert
:hunch: true high
:END:

#+begin_quote
[[per:PraiYut_Jaksan][Prai Yut]] was [[rel:born][born]] on [[dt:2044-2-20:21:22+7][20 feb 2044]] in [[geo:Bangkok_Phuket_Hospital][Bangkok-Phuket Hospital]]
at 9:22 in the evening.
#+end_quote
#+end_example

This should result in the following two quads:

#+begin_src emacs-lisp
("per:PraiYut_Jaksan" "rel:born" "dt:2044-2-20T21:22+7:00"
  ((bmf:id     "802f09ec-03ce-4792-b397-8bb58104f9f5")
   (bmf:owner  "per:deerpig")
   (bmf:stamp  "created:2018-07-04T10:29:56+07:00")
   {bmf:src    "file:projects.org::**heading")
   (bmf:ref    "yut:2044birth-cert")
   (bmf:hunch  "true high")
   (bmf:access "w+w+r+")
   (bmf:agent  "per:deerpig")
   (bmf:acton  "create")))
("per:PraiYut_Jaksan" "rel:born" "geo:Bangkok_Phuket_Hospital")
  ((bmf:id     "91363162-113a-42e3-a322-16a09ae47e3c")
   (bmf:stamp  "created:2018-07-04T10:29:56+07:00")
   (bmf:owner  "per:deerpig")
   {bmf:src    "file:projects.org::**heading") ;; or id#
   (bmf:ref    "yut:2044birth-cert") ;; key to local record
   (bmf:hunch  "true high")
   (bmf:access "w+w+r+")
   (bmf:agent  "per:deerpig")
   (bmf:acton  "create")))
#+end_src

These would be parsed, processed, certainties and
probabilities calculated and woven into to the horcruxes'
graph db.  They will then propagate and be added to all
other horcruxes in the hoard.

I don't know how important it will be for horcruxes to
maintain identical mirror databases. Each horcrux will find
add it's own quad to it's own quadstore, propagate and
integrate locally.  So at any one time, the different dbs
will have a slightly different model, depending on the
context of what they are doing and how up to date they are
relative to the other horcruxes.  I think in the end this
will be a feature not a bug.  It won't result in different
facts being given by different horcruxes as much as slightly
different contexts depending on what each horcrux is doing.

Remember as well that all horcruxes will maintain a
blockchain that will establish concensus on which quad from
which horcrux becomes the canonical id and source for a
quad.




** Ontologies

  - dublin core
  - TEI
  - https://schema.org/
  - http://vocab.org/bio/
  - http://vocab.org/relationship/
  - http://vocab.org/frbr/core
  - http://vocab.org/frbr/extended

** Fnords

I originally wanted to use STMT to mean any statement or
assertion.  We could also use the term 'fact' but that
implies that it is a truth statement.  We certainly don't
want to have binary terms such as fact and lie because in a
none trivial number of cases context determines if something
is true or not.  The Capital of Laos is Vientiene is true
today, but The Capital of Laos is Luang Prabang was also
true in the past.

But we need something more general purpose.  So let's dust
off fnord.

A fnord is an assertion where all possible values for that
assertion are valid.  Not all values; only causally possible
values.

When fnord is observed, the assertion is seen within a
specific context of references to other assertions.  When
this happens the possibility wave collapses to a
single value or a narrow range of possible values and we can
say that within this concept something it true or false and
have a value that represents the magnitude of certainty that
it is true or false.

There are other types of fnords which are types of queries
where the value of a quad is not known.  This is where AI
comes in, and makes a best guess as to what the answer might
be.  This is both for guessing what will happen in the
future, or for filling in blanks in existing local knowledge
to guess what something might be that you can only
indirectly infer or deduce.

This is a core function of BMF-Saltmine as an externalized
local model of the world from a specific context.

People, Groups and AIs will all use this system to
externalize their own "black box" cognitive processes.  In
this way, the hoard's map becomes a means to understand what
and how anyone understands how they see the world and how
they came to those conclusions.  So this is a tool for
off-loading cognitive processing of memories, but also a way
to communicate to others and provide an interopporibility
layer between two different hoards.

Since hoards are shattered into multiple horcruxes
(shatterlings) this is also the mechanism that is used to
merge Δs when horcuxes syncronize.

---

Another aspect of fnords is the "fallacy of obviousness"
which derived from the famous experiment where people were
asked to watch a video and count how many times a basketball
was passed between two people.  In the middle of the video a
person wearing a Gorilla suit strolls into the shot, beats
his chest and walks off.  70% of the people who watch the
video don't see the Gorilla.  Many saw this as a failing in
human cognition -- that we miss the obvious; what is
literally in front of you pounding its chest.

 SEE: cite:felin:2018fallacy,simons:1999gorillas,simons:1999gorilla

But as Teppo Felin suggests, it is not a bug, but a
feature.cite:felin:2018fallacy Many times, there are too
many things going on at once in your visual field, so we
have te ability to filter out everything except what we are
looking for.  Misdirection; the muse of magicians and
pickpockets blinds us to what they don't want us to see.

This ability to focus, to filter out everything except what
we are looking for how we know anything about the world --
how we can pick out patterns in from the riot of sensory
data that we are assaulted with.  The trick is not to only
focus on one thing, but to keep switching focus to include
as many things as possible.

#+begin_quote
This... these... the art historians and the critics talking
about every object and... everything having its own form and
density and... its own character in Flemish paintings, but is that
all there is to it? Do you know why everything does? Because they
found God everywhere. There was nothing God did not watch over,
nothing, and so this... and so in the painting every detail
reflects... God’s concern with the most insignificant objects in
life, with everything, because God did not relax for an instant then,
and neither could the painter then. Do you get the perspective in
this? he demanded, thrusting the rumpled reproduction before
them. — There isn’t any. There isn’t any single perspective, like the
camera eye, the one we all look through now and call it realism, there
... I take five or six or ten... the Flemish painter took twenty
perspectives if he wished, and even in a small painting you can’t
include it all in your single vision, your one miserable pair of eyes,
like you can a photograph, like you can painting when it... when it
degenerates, and becomes conscious of being looked at.

— William Gaddis, The Recognitions 
  cite:gaddis:2012recognitions
#+end_quote




** References

- Felin, T., /The fallacy of obviousness/ (2018).
  cite:felin:2018fallacy 
- Simons, D. J., & Chabris, C. F., Gorillas in our midst:
  sustained inattentional blindness for dynamic events,
  Perception, 28(9), 1059–1074 (1999).
  http://dx.doi.org/10.1068/p281059
  cite:simons:1999gorillas
- Simons, D., & Chabris, C., /Selective attention test
  (video)/ (1999).
  cite:simons:1999gorilla
  
