#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Burr Metadata Framework 
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/bmf/index.org
  :Created: 2017-02-06T09:41@Prek Leap (11.642600N-104.919210W)
  :ID: c10d3a29-5475-45c7-a604-707d89f426c5
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

  - tspaces :: topicspaces
  - dspaces :: doc spaces


Wikipedia title naming conventions


We need a selector mechanism in orgmode for layers to work

can we use org-id for #+insert  ?

* Identities & Roles
:PROPERTIES:
:ID:       7396a2ae-5139-4e84-bedc-fab4bc1b8e5c
:END:

An identity manager could map identities to a virtual, virtual
machine and roles to user accounts on that machine.  In this
way we get all the Unixy goodness that comes with the user
model -- including user home directories, file permissions,
user groups, password, ssh keys etc.

Then email and other accounts are tied to different user
accounts, not to the identity.

So ssh'ing into:

   /ssh:deerpig@HEW1-0756.bxid.org:~/ 

with the proper key-pair would open up that /role/ that would
have it's own storage, email/messaging address and bramble.

Use the same business model as pinboard.in -- one time fee
for life, based on number of users that have signed up.

Since this is supposed to be a personal identity id number,
the number of bxid numbers generated per year must be capped.

Establishing an identity is something that takes time -- new
identities are untrusted by default, but over time, use
patterns and multiple factor authentifications over time
will reinforce an identity until it is something that can be
used to build credit.

Honeypots will be built in -- if you log in and want to see
too much at one time -- you get redirected to a honeypot,
and the honeypot will lock out any other access until the
user resets the account with new keys etc.

Content can be marked public | private | dark  it's like the
Taiwan National Museum, anyone can see anything in the
collection, but you have to ask for it, and there is no
public index of what is in the collection.  No one can get a
dump of all dark content, and there will be a fail2ban
mechanism, as well as an auto destruct feature


* BXID: Easy on the Eye, Ear and Memory 

#+begin_comment
This section is based on section from Sticky Stuff.
#+end_comment


For BMF to work we need a system which is globally unique,
but also is easy to remember and quickly and accurately
written down in awkward situations, like on the street or in
a crowded bar (ie. the five pint rule: if you write it down
in a bar after drinking five pints and can still read it in
the morning it's a good system).

In a paper on the same topic, Sheldon Brahms wrote,

#+begin_quote
Most phone systems decades ago used a combination of
letters and numbers in subscriber identification (phone
numbers). It was common to see phone "exchanges" such as
"Liberty 2" (LI 2) or Walnut 5 (WA 5). Instead of all
numbers, a phone number would be expressed as WA 5-3491.

-- [[http://www.hastingsresearch.com/net/05-nomenclature.shtml][The U.S. Phone Nomenclature System]] | Sheldon Brahms 
#+end_quote

This gave a sing-song, rhythm or lilt to the way a phone
number was said. Often, advertisers used this phenomenon in
jingles, which were also very popular in years past. Phone
numbers were sung along with the rest of the lyric for
client identification, and it lent itself very well to
memory. Businesses would pay extra for phone numbers that
rhymed or otherwise went well with this effect.[BRAHMS]

He recommended development of a similar system. Since we
needed a practical solution for us to continue development
of BMF we sat down and began trying out a number of ideas,
most of which quickly became un-usable, in order to create
enough possible IDs to build a global URI system.

Each BXID which is made up of three letters from the roman
alphabet followed by a number then separated by a dash and
then a four digit integer. GOL2-1023 could be remembered as
Golum 2 Ten Twenty-three. This produces over 175 million
possible ids.

Here are a few examples of BXIDs:

#+begin_example
SBY7-8413
CED2-8235
GUL6-0282
SKD3-0655
QLV8-2404
#+end_example
   

In order for a BXID to be unique, every BXID must belong to
a topicspace. A three letter prefix for a topicspace is
prefixed to a BXID in the same way that namespace prefixes
are used in XML namespaces.

Here are a few examples of BXIDs with topicspaces:


#+begin_example
   aut:SBY7-8413
   geo:CED2-8235
   aut:CED2-8235
   evn:CED2-8235
   evn:GUL6-0282
#+end_example

In the example above, note that the BXID CED2-8235 is used
by the geo, aut and evn topicspaces. These are all valid
universally unique ids because they belong to different
topicspaces.

---

  bxid:HEW1-0756  maps  to id:1dc19191-6072-4799-8017-4319a2236101


  bxid's have a a TTL when issued that renew themselves
  based on useage.  

  If it's used once and then not used for 90 days the bxid
  goes back into the available pool.

  If it is used again x number of times within 90 days it
  will stay active for one year.

  If it's used on a regular basis for one year, it stays
  active for 10 years.

  If it is used on a regular basis for ten years, it will
  stay active for 100 years.

* Properties & topicspaces

Topicspaces are name spaces for collections of information.



:PROPERTIES:
:ID:            c3b6190b-2202-4deb-af82-71d3c6d046dc
:CUSTOM_ID:     per:Carl_Marx
:VERSION:       (milliseconds from epoch)
:CREATED:
:BT:            top:English_Philosopers
:TYPE:          typ:Person
:OWNER:         identity@role
:END:


:BT+:  add to list

:BT~:  add to local/personal list

Entities are record types -- with a schema for what metadata
must, should and can be included and rulesets for processing
records.

** Relationships


- T  :: Top
- B  :: Broader
- N  :: Narrower
- R  :: Related
- U  :: Used For
- *P :: Partitive
- *I :: Instantive
- P  :: Primary Term

- UP   ::
- DOWN :: 
- PREV :: 
- NEXT ::


** Initial Topicspaces

*** Chenla
  - bmf   :: global properties (relationships, entity types, metadata)
  - work  :: created works
  - top   :: topics
  - per   :: persons
  - geo   :: locations
  - event :: events
  - rule  :: rule set
  - duck  :: duck tests
  - blob  :: binary objects -- multimedia - media

*** External Authorities

  - loc   :: loc authorities (title, authority, subject heading)
  - wiki: :: wikipedia articles
  - isbn  :: international standard book number
  - doi   :: 

*** Local Personal

  - folk:   :: personal folksonomies
  - link    :: bookmarks
  - ref     :: local bibliography
  - task    :: (includes alt names, In-Progress, Next, Work,
                Done etc)
  - note    :: (includes diary/journal)
  - msg     :: message (email, tweet, sms, alert (notification), etc)
  - quote   :: 
  - per~    :: (includes contacts 
  - event~  :: (includes, appointments, anniverseries etc)
  - work~   :: local documents
  - blob~   :: local binary objects
  - rule~   :: local cascading rule sets
  - duck~   :: local duck tests
  - scholia :: 
  - gloss   ::
* Scope

One of BMF's primary goals is to capture the surrounding
context of everything in the system.  The primary use case
is in preserving the intended meaning of something (words,
images, sounds etc) when it was created as well as that
meaning changes along with its original context at different
times in history.

For example, in the American Declaration of Independence
written in 17... the term "pursuit of happiness" was
interpreted very differently from the late 20th and early
21st centuries in what would become the United States of
America.  Happiness in the 16th century was closer to the
Epicurian concept of leading a /purposeful/ and productive
life, rather than anything to do with the modern concept of
contentment or bliss.

The other problem is that many references to people, events,
places, and other documents are lost over time.  This can
happen very quickly.  A legal dispute involving
correspondence over a twenty year old internal project at a
company that has long been out of business may reference
people, reports and events (eg. phone calls, meetings etc)
that there is no longer any record of outside of someone's
distant memory of events.  Human memory is notoriously
inacurrate and recollection of events changes in the mind
over time.  We remember the past relative to and interpreted
by our present context, not as it actually happened or even
as we experienced it at the time.

Preserving references made within things that are stored is
relatively straight forward, but quickly becomes resource
intensive.  It also poses the problem of where do you stop?
If a letter preserves or records all of the people, places
and events in a document (this is called a /hop/ or a level
of separation) do you then save all of the references made
in in the referring source?  How far does one go?  Even
following references three levels deep borders would require
a very significant amount of resources.

logarithmic 

[[https://en.wikipedia.org/wiki/Logarithmic_scale][Logarithmic scale]] | Wikipedia

In the small world problem -- it is thought that every
person on the planet is separated by anywhere from 6-8
levels.  

At some point you start running into the /Map and Territory/
problem. 

** Meaning as Internal Interpretation

Preserving context is a useful thing to do -- but how does
that relate to meaning?  Is meaning something that can be
objectively defined and recorded?  Or is it, like knowledge,
a constantly shifting thing that can no more captured than
smoke in your hand.

Meaning is a slippery word at best.  There are various types
of meaning defined in linguistics, in semiotics, in
philosophy there is existential meaning etc.

It's useful, for general purposes, to define meaning as a
kind of internal mental interpretation relative to the state
that the mind is in at the moment of interpretation.
Determining meaning is a kind of decsion -- taking in what
is happening now, and mixing it together with what is
remembered and what has been learned before.  Slosh it all
together and shake well and you get a meaning, or at least a
snapshot of what that meaning was for the observer at the
moment of interpretation.

#+begin_quote
The sense that sentient creatures have that the various
objects of our universe are linked is commonly referred to
as a person's sense of "meaning". This is the sense of
meaning at work when asking a person when they leave a
theater, "What did that movie mean to you?" In short, the
word "meaning" can sometimes be used to describe the
interpretations that people have of the world.

-- [[https://en.wikipedia.org/wiki/Meaning_(non-linguistic)][Meaning (non-linguistic)]] | Wikipedia
#+end_quote


So let's move the concepts of meaning and knowledge out of
our model and use the terms to refer to particular states of
collections of information that have gone through iterative
processes of building cognitive models of the world.

What we will focus on is preserving context.  We have
already discussed preserving references but how we do this
is not as straight forward as it might seem at first.

We will call /references/ that are matched with a pointer
to the source of the reference or a definition or record
describing them /links/.  

Links can be broken down into a number of different types:

  - address      :: a place where a resource is located -- this is
                    in effect, the venerable hyperlink in
                    all it's glory. hyperlinks transport you
                    from one location to another.
  - relationship :: the relationship between two things
  - definition   :: a resource that defines what something is.
  - value        :: a key-value pair
  

** The Scope Model

Clearly /meaning/ is not what we are striving for

The scope model is central to BMF.  In BMF, in theory, every
Burr must define it's scope.  In most cases this will be
achieved through inheritance in the cascade, but it still
has to be defined at top levels of trees.

Scope is defined through three attributes: /Level of Detail/
(LOD) Point of View (POV) and Rate of Change (ROC).



** Level of Detail (LOD)

LOD is determined by how close or far the observer is from
what is being defined.  The closer you are, the more detail
you see, the farther away, the less detail you see.

There is no one size fit all for defining LOD.  

In 3-D modeling this is achieved by defining the polygon
count of a model, relative to the distance the model is
placed from the camera.  The closer the camera gets the more
polygons a model can be observed.

In imaging, especially arial and satellite imaging, LOD is
defined by the resolution of a single pixel in an image.  In
astronomy, a single pixel might represent an entire planet
or a star or even a galaxy.  For a satellite image, a pixel
might be anywhere from a kilometer, to a few meters.

In printed matter, such as books and magazines, LOD is
measured sort of like seeing a forest, in which you can only
see each tree as a thin trunk or canopy, and then only the
trees that are at the edge of the forest.  The trees inside
the forest are completely hidden.  The same goes for books
in a brick and mortar library.  From outside the stacks, all
you can see are rows of shelves with ranges of classifiction
call numbers for books in each row.  But the books are
completely hidden.  When you get closer you can see the
books on the shelves of a row, but only the spines, which
can only be distinguished from each other by color and
binding type.  You'll usually be able to pick out which
books are older, which were cheaply printed paperbacks and
which are quality constructed hard-backs.  Get a little
closer and you can see a little metadata for each book --
it's title, author and a logo for the publisher.  Take a
book off the shelf and if there is dest jacket you can see
the fill title, author, perhaps an illustration, and a blurb
on the back, open the cover and the inside sleave of the
jacket will have a summary of the book.  Open to the title
page and the publishing information on the opposite side of
the title page and you will see detailed, structured
metadata on when the book was published, it's publishing
history, and perhaps a suggested library catalog record for
the book. Getting closer, you open the book to the Table of
Contents to see the overall organization of the book.  And
then getting closer and you are in the actual text of the
book -- at full resolution.

LOD could also refer to levels of expertise -- a layman or
beginner might only see a simple outline of a topic which
does not use technical terms.  But as skills increase,
so will the level of detail.  This is one half of leaning --
the other half is in the level of proficiency through
memorization and practice which is not only a measure of the
level of detail but a measure of mastery -- which is handled
by ROC attribute.

LOD establishes the distance of an observer to what is being
defined.  LOD is a measure of how much detail can be
included or observed, but also includes the orientation of
an observer relative to what is being defined in Cartesian
or Hilbert space which determines the level of detail that
can be observed.  This type of orientation is traditionally 
thought to be part of the Point of View (POV) of the
observer but is better suited to LOd than POV as we will see
in the next section.

** Point of View (POV)

LOD can be thought of as a subset of POV, but not all POVs
are a meaure of orientation, distance and observed detail.

A POV can be thought of as a filter that determines what can
be obseved.  In other words, the POV are the blinders that
determine what is observed.  For example a dog can smell and
hear things that a human can not.  Many animals such as
birds are sensitive to electromagnetic fields that allow
them to navigate in ways that are outside of human
perception.  Conversely, many adult humans (of normal
intelligence who are not suffering from self-inflicted
cognitive dissonance) have cognitive, reasoning and
deductive skills that are orders of magnitude greater than
many of our fellow mammals.  A dog that has wound it's lead
around the tree that it has been tied to can not understand
that by reversing the path that got it intangled in the
first place, will get it out of its present predicament.

POV defines the specific limitations of an observer's
ability to observe relative to what is being defined.

These limitations can include:

  - senses     :: visual, audio, smell
  - cognition  :: the ability to process information
  - cultural   :: language, social norms, shared memories
  - experience :: compare things observed to simular thing
                  observed previously.

** Rate of Change (ROC)

ROC can also be seen as a subset of POV

Pacing layers -- the time frame that something is observed
in determines what is seen -- a human watching a humming
bird in flight can only see the bird's wings as a blur.  But
if a high frame rate video of the humming bird is taken that
is faster than the 24fps that the human eye can discern,
then you can clearly see the wings and how they move in
flight.

From the ROC of a tree, the humming bird is all but
invisible, with only the evidence that someone the nector in
it's flowers (if it's a flowering tree) has been
mysteriously removed and it's pollen spread.

From the ROC of our sun, all life on earth is only apparent
as the greening of the third large rock that orbits it over
the last several billion years.

Like in an image, ROC is based largely on the base unit of
observable time.  For a humming bird in flight that unit
will be in thousands of a second, for a tree, years and
decades, for the sun, hundreds of millions of years.

As in LOD, there are a wide number of scales that can be
used to define ROC, from Stewart Brand's Pacing Layers for
Civilizations, and his Shearing layers for the life of
buildings.  There are also scales of proficiency in a skill
-- for someone learning to play an instrument, or to touch
type, or speak a language or a martial art, the speed and
accuracy that one can perform at, without effort is a
spectrum from beginner to master

** Scheme Requirements

All values for LOD, POV and ROC MUST be given as a value
within a defined Scheme or Scale.

So we will MUST define different scales or Schemes
for different types of context, media and information.

Schemes for each class of Scheme MUST be appled to an entire
topicspace.

Interoperability between Schemes SHOULD be defined in a
ruleset, so that Scheme A is defined relative to Scheme B.
Exceptions to this requirement is expected to be rare.  Even
when a particular Scheme is the first to be defined, the
schem MUST be based on empirical observations and backed up
with references, and authorities.
* Wrapper

Our goal here is to create a wrapper for content payload
that can be used in the same way that the wrapper for
email/news works, as well as an archival format.

The wrapper will also double as an index of the content in
the form of a property graph,

  - wrapper
  - index
  - payload



** Google's Protocol Buffers

  - [[https://developers.google.com/protocol-buffers/][Protocol Buffers]] | Google Developers
  - [[https://github.com/google/protobuf/releases][google/protobuf]]  | Github

#+begin_src 
message SearchRequest {
  string query = 1;
  int32 page_number = 2;
  int32 result_per_page = 3;
}
#+end_src


I like that the types are defined upfront, which may or may
not effect readability....

** Internet Archive | ARC Format

  - [[http://fileformats.archiveteam.org/wiki/WARC][WARC - Just Solve the File Format Problem]]
  - [[http://digitalpreservation.gov/formats/fdd/fdd000236.shtml][WARC]]   | Web ARChive file format
  - [[https://archive.org/web/researcher/ArcFileFormat.php][ARC File Format Reference]] | Internet Archive
  - [[http://www.digitalpreservation.gov/formats/fdd/fdd000235.shtml][ARC_IA]] | Internet Archive ARC file format

Tools

  - [[https://github.com/chfoo/warcat][chfoo/warcat]] | Github

* Horcrux

A Horcrux is a self-executing container that contains holons
which are both self contained wholes as well as parts of
larger wholes.

  - hoard (25, 50, 100, 25, 500 MB)
  - saltmine
  - picolisp
  - alpine linux
  - container (docker or rkt)

A hoard is simular an ARC/WARC file in that it is a file in
which chunks are concated -- write once, no delete.

Each chunk is a /holon/ that is made up of an:

  - envelop
  - index
  - payload

Envelops are simular to a email/nntp header with basic
information including ids, checksums etc.

An index is a bag of property triples that index what is in
the payload -- each triple is a /fnord/.

The payload can be:

  - text/code
  - data (eg tabular)
  - code
  - blob
  - empty

Every horcrux will not only have an api, but will also have
a minimal shell that can be ssh'd into.  Still not sure that
we need that -- but since every horcrux is also a fragment
of an identity, each horcrux will need all of the unixy user
account stuff that is needed as part of identity, role and
permission management.

Each horcrux is a snowflake -- you'll never back up or
duplicate an entire horcrux, rather all of the holons in
each horcrux will maintain a set number of distributed
copies of themselves which will reside in any number of
horcruxes.  There will not be multiple copies of a holon in
the same horcrux, though it might be possible that different
versions of the same holon may reside in the same horcrux.

----

Horcruxes come in four flavours:

 - hoards :: hold the data and do first pass processing on
             that data.
 - ducks  :: are tangled from hoards and are designed to
             processing holons using rulesets.
 - maps   :: collect output from ducks into world-maps that
             are then available to applications.
 - export :: export payloads in holons to end-user formats
             -- generate latex, pdfs, static sites, rss etc.

----

What we're still missing is how the horcruxes will talk to
each other and how you will find information that is in a
given horcrux.

   are we talking about routing here?  that if you ping a
   holon, the horcruxes that of all the copies of that holon
   will ping back?

   if so, in effect, a horcrux is functionally a host --
   which is not such a stretch here -- but you should not be
   able to traceroute a horcrux -- pings are broadcast, and
   listened for by horcruxes -- and when horcruxes are
   created there shouldn't be any way to know where they are
   hosted.

   if you request a holon -- it is sent, and then listened
   for by the requesting application.  Your don't know where
   the horcrux is....  

   But then how can you ssh into a horcrux without
   establishing and end-to-end encrypted tunnel?


And the system needs to provide privacy as well as
transparency.  Any content can be either public, private or
limited to a specific group.

We also need to understand how the system establishes trust
without having to trust in any other party.

---

bitcoin is brute force trust -- there are no shades of gray

and it's all open -- what if we substitute all that heavy
computation with complexity and any number of doors that
need to be passed through -- and keys.

but those locks only open if all the other locks in /front/ of
them have not been tampered with.  huh?  you can never only
unlock the door in front of you, it must also be able to
lock the last door as well?

need to think about all of that -- I'm fucking tired right
now.

but what is needed in to establish reputation which needs to
be established over time -- replace the heavy computation
with reputation that requires a lot of work and time to
establish and the more the system is used, the less likely
that you'll be able to fake a reputation -- reputation must
be independent of motive -- even if you want to be a bad
actor, you can't build a reputation unless you are doing the
right thing.




